server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db6?serverTimezone=UTC
    username: root
    password: '0826'

mybatis:
  type-aliases-package: cn.hrsweb.provider.pojo
