server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db6?serverTimezone=UTC
    username: root
    password: '0826'
  application:
    name: PROVIDER-SERVER

mybatis:
  type-aliases-package: cn.hrsweb.provider.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true # 其他服务获取地址时获取ip而不是hostname
    ip-address: 127.0.0.1