server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db6?serverTimezone=UTC
    username: root
    password: '0826'
  application:
    name: provider-server

mybatis:
  type-aliases-package: cn.hrsweb.provider.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
