server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    #instance:
      #ip-address: 127.0.0.1 指定自己的ip信息，不指定的话会自己寻找
    registry-fetch-interval-seconds: 10  # 每隔10秒重新获取并更新数据
spring:
  application:
    name: CONSUMER-SERVER
hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000   #设置hystrix的超时时间为6000秒

feign:
  circuitbreaker:
    enabled: true # 开启Feign熔断功能